### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by zburu** [zburu/Anghunk#1]
>站点名称: 不如吃茶去
>站点链接: https://imhan.cn

**Comment by xiamuguizhi** [comment]
- 站点名称: 叶开博客
- 站点链接: [叶开.cn](https://xn--qpru0x.cn/)

**Comment by xiaoxiangtear** [comment]
大佬好，我启用这个主题后，刷新网页提示“Database Query Error”，请问是需要在你的主题文件夹中php等文件修改数据库信息吗？还是我其他的设置出错了...

**Comment by xiaoxiangtear** [comment]
文件夹名字是Anghunk

**Comment by anghunk** [comment]
> 大佬好，我启用这个主题后，刷新网页提示“Database Query Error”，请问是需要在你的主题文件夹中php等文件修改数据库信息吗？还是我其他的设置出错了...

你好，我看了一下你fork的是我之前的代码，这段时间我又更新了不少，可能某个时间段出了一个bug，在我不知情的情况下。

建议你fork最新的主题。或者还有别的可能性，typecho程序需要升级1.2

**Comment by anghunk** [comment]
> > 大佬好，我启用这个主题后，刷新网页提示“Database Query Error”，请问是需要在你的主题文件夹中php等文件修改数据库信息吗？还是我其他的设置出错了...
> 
> 你好，我看了一下你fork的是我之前的代码，这段时间我又更新了不少，可能某个时间段出了一个bug，在我不知情的情况下。
> 
> 建议你fork最新的主题。或者还有别的可能性，typecho程序需要升级1.2

我这便边用别的网站测试了，可以正常启用，没有遇到报错问题，应该是你本地的问题，看看是不是升级权限的问题，upload文件

**Comment by anghunk** [comment]
> 大佬好，我的主题后，网页提示修改“数据库查询错误”，请问这个是需要在你的其他数据库文件夹中的其他主题信息中吗？还是我的设置错误了...

#3

**Comment by peachrl** [comment]
站点名称: peachRL的小站
站点链接: [https://blog.wanyijizi.com/](https://blog.wanyijizi.com/)

但是我现在进不去后台了…似乎把 cdn 关掉才能好 😕

**Comment by peachrl** [comment]
大佬好！我刚刚拉取了最新的主题。我想请问一下我的标签页标签消失了怎么办？
![image](https://user-images.githubusercontent.com/49336598/165103460-5a7a3976-03f3-496b-a8fa-e0f6d1cdf1d2.png)

**Comment by anghunk** [comment]
有没有在后台设置页面类型>标签



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月25日 21:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [anghunk/Typecho-theme-Anghunk] 欢迎使用主题的小伙伴留下你的站点！ (Issue #1) |

大佬好！我刚刚拉取了最新的主题。我想请问一下我的标签页标签消失了怎么办？

**Comment by anghunk** [comment]
> 大佬好！我刚刚拉取了最新的主题。我想请问一下我的标签页标签消失了怎么办？ ![image](https://user-images.githubusercontent.com/49336598/165103460-5a7a3976-03f3-496b-a8fa-e0f6d1cdf1d2.png)

某次更新我修改tags页面的模版路径，所以拉取最新的主题后，需要在后台独立页面重新设置一下。

**Comment by peachrl** [comment]
> > 大佬好！我刚刚拉取了最新的主题。我想请问一下我的标签页标签消失了怎么办？
> 
> 某次更新我修改tags页面的模版路径，所以拉取最新的主题后，需要在后台独立页面重新设置一下。

果然好啦！谢谢大佬~
