### ISSUE TITLE
上一篇文章与下一篇文章有bug

### ISSUE THREAD

**Issue by lhuang001** [zburu/Anghunk#5]
Git编号： 2de59e5
问题：打开第一篇文章时，“上一篇文章”显示空白。同理最后一篇文章的“下一篇文章”显示空白
问题截图：
![image](https://user-images.githubusercontent.com/21240907/173221920-42266e47-834e-41b7-b7f8-51e7e217395c.png)

该问题已在[PR](https://github.com/zburu/Anghunk/pull/4)中处理，请您抽出时间code review。

**Comment by zburu** [comment]
pr已处理
