### ISSUE TITLE
markdown代码块的第一行多了一个空格

### ISSUE THREAD

**Issue by lhuang001** [zburu/Anghunk#6]
您好，我非常喜欢这个主题，但在使用是发现markdown代码块的第一行会多出一个空格，看起来很别扭。
希望您能在百忙之中抽出时间修复。

Git编号：[2de59e5](https://github.com/zburu/Anghunk/commit/2de59e5a3990ff515738ae769a2aabbe65d90571)
问题截图：
![image](https://user-images.githubusercontent.com/21240907/173222814-a700b1a7-0549-434b-bf8a-15153a3bc6ed.png)

**Comment by zburu** [comment]
这个细节没有做好，明天修复一下。

ps: 今天在火车上，刚才你提的那个pr我合并了

**Comment by lhuang001** [comment]
好的，辛苦大佬了。

**Comment by zburu** [comment]
@lhuang001 [#434c675ae2aa536510d4206278efa1307373de04](https://github.com/zburu/Anghunk/commit/19870b1675415f98302cdd8e0895988ab5a25c9a#diff-4912e132d99299e24f6a9861376c2d615a85125f148d791ccd08e2f710b76034)

**Comment by lhuang001** [comment]
已更新，问题解决。辛苦大佬了，感动~
